START TRANSACTION;

--  RSS 

SELECT new_rss_source('Kaspersky official blog', 'https://www.kaspersky.co.uk/blog/feed/'); -- 
SELECT new_rss_source('The Cloudflare Blog', 'https://blog.cloudflare.com/rss/'); -- 
SELECT new_rss_source('Blog – Hackaday', 'https://hackaday.com/blog/feed/'); -- 
SELECT new_rss_source('Attack Blogs – Horizon3.ai', 'https://horizon3.ai/category/attack-research/attack-blogs/feed/'); -- 
SELECT new_rss_source('SecurityWeek', 'https://www.securityweek.com/feed/'); -- 
SELECT new_rss_source('BleepingComputer', 'https://www.bleepingcomputer.com/feed/'); -- 
SELECT new_rss_source('CSHub Reports', 'https://www.cshub.com/rss/reports'); -- 
SELECT new_rss_source('CSHub Articles', 'https://www.cshub.com/rss/articles'); -- 
SELECT new_rss_source('TheRegister.com', 'https://www.theregister.com/security/headlines.atom'); -- 
SELECT new_rss_source('Biz & IT - Ars Technica', 'https://feeds.arstechnica.com/arstechnica/technology-lab'); -- 
SELECT new_rss_source('Help Net Security', 'https://www.helpnetsecurity.com/feed/'); -- 
SELECT new_rss_source('Phoronix', 'https://www.phoronix.com/rss.php'); -- 
SELECT new_rss_source('Qualys, Inc. News Releases', 'https://investor.qualys.com/rss/news-releases.xml'); -- 
SELECT new_rss_source('Microsoft Azure Blog', 'http://azure.microsoft.com/en-us/blog/feed'); -- 
SELECT new_rss_source('Microsoft Azure Quantum Blog', 'https://azure.microsoft.com/en-us/blog/quantum/feed'); -- 
SELECT new_rss_source('Microsoft Security Blog', 'https://www.microsoft.com/en-us/security/blog/feed/'); -- 
SELECT new_rss_source('Microsoft Open Source Blog', 'https://opensource.microsoft.com/blog/feed/'); -- 
SELECT new_rss_source('Huntress Blog', 'https://www.huntress.com/blog/rss.xml'); -- 
SELECT new_rss_source('WeLiveSecurity', 'http://feeds.feedburner.com/eset/blog?format=xml'); -- 
SELECT new_rss_source('Bitdefender Labs', 'https://www.bitdefender.com/nuxt/api/en-us/rss/labs/'); -- 
SELECT new_rss_source('Threat Intelligence', 'https://feeds.feedburner.com/threatintelligence/pvexyqv7v0v'); -- 
SELECT new_rss_source('Project Zero', 'https://googleprojectzero.blogspot.com/feeds/posts/default'); -- 
SELECT new_rss_source('Zero Day Initiative - Blog', 'https://www.zerodayinitiative.com/blog/?format=rss'); -- 
SELECT new_rss_source('ZDI: Upcoming Advisories', 'https://www.zerodayinitiative.com/rss/upcoming/'); -- 
SELECT new_rss_source('ZDI: Published Advisories', 'https://www.zerodayinitiative.com/rss/published/'); -- 
SELECT new_rss_source('Cisco Talos Blog', 'https://blog.talosintelligence.com/feed/'); -- 
SELECT new_rss_source('Sekoia Blog', 'https://www.sekoia.com/blog/rss.xml'); -- 
SELECT new_rss_source('Cybercrime Magazine', 'https://cybersecurityventures.com/feed/'); -- 
SELECT new_rss_source('cybercrime/malcode – Lifeboat News: The Blog', 'https://lifeboat.com/blog/category/cybercrime-malcode/feed'); -- 
SELECT new_rss_source('G Data SecurityBlog (english)', 'https://feeds.feedblitz.com/GDataSecurityBlog-EN&x=1'); -- 
SELECT new_rss_source('The CCG Blog', 'https://ccgnludelhi.wordpress.com/feed/'); -- 
SELECT new_rss_source('Cybertrace Blog', 'https://www.cybertrace.com.au/blog/feed/'); -- 
SELECT new_rss_source('Malwarebytes', 'https://www.malwarebytes.com/blog/feed/index.xml'); -- 
SELECT new_rss_source('Intel 471 Blog', 'https://intel471.com/blog/feed'); -- 
SELECT new_rss_source('Trend Micro | Newsroom (Cyberthreat )', 'https://newsroom.trendmicro.com/cyberthreat?pagetemplate=rss'); -- 
SELECT new_rss_source('Trend Micro | Newsroom (Education)', 'https://newsroom.trendmicro.com/education?pagetemplate=rss'); -- 
SELECT new_rss_source('Trend Micro | Newsroom (Research)', 'https://newsroom.trendmicro.com/news-releases?pagetemplate=rss&category=787'); -- 
SELECT new_rss_source('ReversingLabs Blog', 'https://www.reversinglabs.com/blog/rss.xml'); -- 
SELECT new_rss_source('Checkmarx: Zero Type', 'https://checkmarx.com/feed/?post_type=zero-post'); -- 
SELECT new_rss_source('Checkmarx', 'https://checkmarx.com/feed/'); -- 
SELECT new_rss_source('Research Archives - The Citizen Lab', 'https://citizenlab.ca/category/research/feed'); -- 
SELECT new_rss_source('The Citizen Lab', 'https://citizenlab.ca/feed'); -- 
SELECT new_rss_source('Cloud Blog', 'https://cloudblog.withgoogle.com/rss/'); -- 
SELECT new_rss_source('The Keyword', 'https://blog.google/rss/'); -- 
SELECT new_rss_source('Zimperium Blog', 'https://zimperium.com/blog/rss.xml'); -- 
SELECT new_rss_source('Promon.io Blog', 'https://promon.io/security-news/rss.xml'); -- 
SELECT new_rss_source('Cyble', 'https://cyble.com/blog/feed/'); -- 
SELECT new_rss_source('Securonix Blog', 'https://www.securonix.com/blog/feed/'); -- 
SELECT new_rss_source('The Trail of Bits Blog', 'https://blog.trailofbits.com/index.xml'); -- 
SELECT new_rss_source('RedTeam Pentesting Blog', 'https://blog.redteam-pentesting.de/posts/index.xml'); -- 
SELECT new_rss_source('Talkback Resources', 'https://talkback.sh/resources/feed/'); -- 
SELECT new_rss_source('Frank DENIS random thoughts', 'https://00f.net/atom.xml'); -- 
SELECT new_rss_source('DefenseScoop', 'https://defensescoop.com/feed/'); -- 
SELECT new_rss_source('nns.ee', 'https://blog.nns.ee/index.xml'); -- 
SELECT new_rss_source('Peter Norvig Blog', 'https://norvig.com/rss-feed.xml'); -- 
SELECT new_rss_source('Margin Research', 'https://margin.re/blog/rss/'); -- 
SELECT new_rss_source('cocomelonc Blog', 'https://cocomelonc.github.io/feed.xml'); -- 
SELECT new_rss_source('Thorsten Ball', 'https://thorstenball.com/atom.xml'); -- 
SELECT new_rss_source('APNIC Blog', 'https://blog.apnic.net/feed/'); -- 
SELECT new_rss_source('Research & Tradecraft Archives - SpecterOps', 'https://specterops.io/blog/category/research/feed/'); -- 
SELECT new_rss_source('watchTowr Labs', 'https://labs.watchtowr.com/feed/'); -- 
SELECT new_rss_source('חדשות סייבר - ארז דסה', 'https://rss.app/feeds/Ho4gIVhEXQwiIoOx.xml'); -- A telegram channel
SELECT new_rss_source('Three Buddy Problem', 'https://feeds.fireside.fm/securityconversations/rss'); -- Actually a podcast 
SELECT new_rss_source('Defense Tech Week Newsletter', 'https://newsletter.defensetech-week.com/feed/'); -- 
SELECT new_rss_source('lyra''s epic blog!', 'https://lyra.horse/blog/posts/index.xml'); -- 
SELECT new_rss_source('Cyber Threat Alliance', 'https://www.cyberthreatalliance.org/blog/feed'); -- 
SELECT new_rss_source('PentesterLab', 'https://pentesterlab.com/blog/feed'); -- 
SELECT new_rss_source('Loophole Labs Blog', 'https://loopholelabs.io/blog/rss.xml'); -- 
SELECT new_rss_source('Blog - LiveOverflow', 'https://liveoverflow.com/topic/blog/feed/'); -- 
SELECT new_rss_source('Open Source Security','https://seclists.org/rss/oss-sec.rss'); -- 
SELECT new_rss_source('Anthropic Engineering Blog', 'https://raw.githubusercontent.com/conoro/anthropic-engineering-rss-feed/main/anthropic_engineering_rss.xml'); -- Not official
SELECT new_rss_source('Anthropic Research', 'https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_research.xml'); -- Not official
SELECT new_rss_source('Anthropic Frontier Red Team Blog', 'https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_red.xml'); -- Not official
SELECT new_rss_source('OpenAI Research News', 'https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_openai_research.xml'); -- Not official
SELECT new_rss_source('Google DeepMind Blog', 'https://deepmind.google/blog/rss.xml'); -- 
SELECT new_rss_source('Thinking Machines Lab', 'https://thinkingmachines.ai/blog/index.xml'); -- 

--  Failed to parse
--  [!] Error for 'https://securityscorecard.com/blog/feed/'
--  [!] Error for 'https://securityscorecard.com/resources/research/feed'

--  YouTube

SELECT new_youtube_source('John Hammond', 'UCVeW9qkBjo3zosnqUbG7CFw'); -- 
SELECT new_youtube_source('Low Level', 'UC6biysICWOJ-C3P4Tyeggzg'); -- 
SELECT new_youtube_source('Live Overflow', 'UClcE-kVhqyiHCcjYwcpfj9w'); -- 
SELECT new_youtube_source('Off By One Security', 'UCc8gr33-DyCZ6gAmqdcyzgA'); -- 
SELECT new_youtube_source('PC Security', 'UCKGe7fZ_S788Jaspxg-_5Sg'); -- 
SELECT new_youtube_source('IppSec', 'UCa6eh7gCkpPo5XXUDfygQQA'); -- 
SELECT new_youtube_source('NahamSec', 'UCCZDt7MuC3Hzs6IH4xODLBw'); -- 
SELECT new_youtube_source('Nir Lichtman', 'UCAMu6Dso0ENoNm3sKpQsy0g'); -- 
SELECT new_youtube_source('Security Weekly - A CRA Resource', 'UCg--XBjJ50a9tUhTKXVPiqg'); -- 
SELECT new_youtube_source('Checkmarx Zero', 'UCZbxYOLa6M90BTvA6yYawLw'); -- 
SELECT new_youtube_source('TheShyHat', 'UCNqIidYyWi9Zbr48VV1Xr_g'); -- 
SELECT new_youtube_source('Black Hat', 'UCJ6q9Ie29ajGqKApbLqfBOg'); -- 

--  Mastodon

SELECT new_mastodon_source('GossiTheDog', 'cyberplace.social'); --  
SELECT new_mastodon_source('jimmychappell', 'infosec.exchange'); --  
SELECT new_mastodon_source('sirdarckcat', 'infosec.exchange'); --  
SELECT new_mastodon_source('_marklech_', 'infosec.exchange'); --  
SELECT new_mastodon_source('maldr0id', 'infosec.exchange'); --  
SELECT new_mastodon_source('tomchop', 'infosec.exchange'); --  
SELECT new_mastodon_source('hackndo', 'infosec.exchange'); --  
SELECT new_mastodon_source('imlordofthering', 'infosec.exchange'); --  
SELECT new_mastodon_source('sphynx', 'infosec.exchange'); --  
SELECT new_mastodon_source('trailofbits', 'infosec.exchange'); --  
SELECT new_mastodon_source('secwolf404', 'mas.to'); --  
SELECT new_mastodon_source('atoponce', 'fosstodon.org'); --  
SELECT new_mastodon_source('tao', 'mathstodon.xyz'); --  

COMMIT;
